workflows:
    ios-hello-world-no-code-signing:
      name: Testing
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'master'
            include: true
            source: true
      scripts:
        - name: Build iOS
          script: |
            cd $FCI_BUILD_DIR
            xcodebuild build -project "helloworld.xcodeproj" \
            -scheme "helloworld" \
            CODE_SIGN_INDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      artifacts:
        - build/**/*.app
        - /tmp/xcodebuild_logs/*.log
