workflows:
  swift-hello-world:
    name: Testing
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - |
        xcodebuild build -project "helloworld.xcodeproj" \
        -scheme "helloworld" \
        CODE_SIGN_INDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/*.app
      - /tmp/xcodebuild_logs/*.log
