workflows:
    ios-hello-world:
      name: Code signing
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
        branch_patterns:
          - pattern: 'wo_codesign'
            include: true
            source: true
      scripts:
        - xcodebuild -project "helloworld.xcodeproj" -scheme "helloworld" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build
      artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
    ios-hello-world-no-code-signing:
      name: Testing
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'master'
            include: true
            source: true
      scripts:
        - |
            cd $FCI_BUILD_DIR
            xcodebuild build -project "helloworld.xcodeproj" \
                   -scheme "helloworld" \
                   CODE_SIGN_INDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO
      artifacts:
        - build/**/*.app
        - /tmp/xcodebuild_logs/*.log
